name: reel_ai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # Firebase
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  firebase_storage: ^12.4.2
  cloud_functions: ^5.3.2
  
  # Routing
  go_router: ^14.7.2
  
  # UI Components
  cached_network_image: ^3.4.1
  cached_network_image_web: ^1.3.1
  flutter_cache_manager: ^3.3.1
  flutter_staggered_grid_view: ^0.7.0
  timeago: ^3.6.0
  
  # Video Player & Sharing
  video_player: ^2.8.1
  video_player_web: ^2.1.2
  share_plus: ^10.1.4
  
  # Utils
  http: ^1.1.0
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  path: ^1.9.0
  mime: ^2.0.0
  js: ^0.7.1
  ffmpeg_kit_flutter: ^6.0.3
  
  # File Picker
  file_picker: ^6.1.1
  
  # Environment Configuration
  flutter_dotenv: ^5.1.0
  google_fonts: ^6.2.1
  provider: ^6.1.1
  url_launcher: ^6.3.1
  uuid: ^4.2.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true 