name: reel_ai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # Firebase
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.4.1
  
  # UI Components
  cached_network_image: ^3.3.0
  cached_network_image_web: ^1.1.0
  flutter_cache_manager: ^3.3.1
  flutter_staggered_grid_view: ^0.7.0
  
  # Video Player & Sharing
  video_player: ^2.8.1
  video_player_web: ^2.1.2
  share_plus: ^7.2.2
  share_plus_web: ^3.1.0
  
  # Utils
  http: ^1.1.0
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  path: ^1.8.3
  mime: ^1.0.6
  js: ^0.6.7
  ffmpeg_kit_flutter: ^6.0.3
  
  # Environment Configuration
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true 