// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwu4wrYZoSDwTUocfIYPKdYfcAfhIXBrU',
    appId: '1:951652872306:web:56d94e6fc1e894ae9b92eb',
    messagingSenderId: '951652872306',
    projectId: 'reel-ai-dev',
    authDomain: 'reel-ai-dev.firebaseapp.com',
    storageBucket: 'reel-ai-dev.firebasestorage.app',
    measurementId: 'G-ZY9B8T926D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEGXGSctfLi7b0CZiwFfpqMyvT3zIdqSE',
    appId: '1:951652872306:android:2257bb41901f93289b92eb',
    messagingSenderId: '951652872306',
    projectId: 'reel-ai-dev',
    storageBucket: 'reel-ai-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh3yFLBPL72xGS21xfGakdLe4dwV5Nk6k',
    appId: '1:951652872306:ios:7250f504c04c35439b92eb',
    messagingSenderId: '951652872306',
    projectId: 'reel-ai-dev',
    storageBucket: 'reel-ai-dev.firebasestorage.app',
    iosBundleId: 'com.gauntletai.freshman.reelai',
  );
}
